// icons.ts — CdIcon file manifest.
//
// Every glyph is a standalone SVG file under public/icons/. This manifest maps each IconName to
// its file and tells CdIcon how to render it:
//
//  - mode 'mask': CSS mask-image + background-color. For monochrome files — preserves the dynamic
//    `color` prop exactly like the old inline-SVG registry did (mask alpha keeps per-path
//    fill-opacity, e.g. trash's 22% body tint renders as 22% of the passed color).
//  - mode 'img': plain <img>. For the design batch's two-tone brand files whose baked ink+olive
//    coloring IS the design (Zoe's 2026-07-11 hybrid ruling): brand-identity glyphs render at
//    their fixed design colors; the `color` prop is ignored, and active/inactive states dim via
//    opacity at the call site (see CdBottomNav) instead of recoloring. Semantic-recolor glyphs
//    (trash's danger red, copy/pencil grays, gear) stay 'mask' so callers keep color control.
//
// File provenance: public/icons/brand/* and the NN-numbered public/icons/utility/* files are
// design-delivered; the rest of utility/ is generated by `node scripts/export-icons.mts` from
// scripts/icon-glyph-registry.ts (the old inline path registry, kept as the drawing source for
// glyphs the design batch doesn't cover yet). Chevrons are one design file baked into three
// direction variants at export time — no runtime rotation, so call sites' own expand/collapse
// `transform: rotate()` animations keep working.
import { publicAssetPath } from '@/utils/public-assets'

export type IconName =
  | 'close'
  | 'plus'
  | 'copy'
  | 'pencil'
  | 'trash'
  | 'chevron-left'
  | 'chevron-right'
  | 'chevron-down'
  | 'journal'
  | 'spark'
  | 'bell'
  | 'target'
  | 'search'
  | 'calendar'
  | 'clock'
  | 'check'
  | 'image'
  | 'arrow-up'
  | 'repeat'
  | 'location'
  | 'notes'
  | 'info'
  | 'sync'
  | 'mail'
  | 'reset'
  | 'spark-mono'
  | 'journal-plain'
  | 'x-small'
  | 'pencil-small'
  | 'calendar-alt'
  | 'tomato'
  | 'view-day'
  | 'view-week'
  | 'view-month'
  | 'view-list'
  | 'gear'
  | 'brush'
  | 'globe'
  | 'star'
  | 'layers'
  | 'home'
  | 'lock'
  | 'heart'
  | 'work'
  | 'users'
  | 'school'
  | 'bulb'
  | 'eye'
  | 'note'
  | 'shield'

export interface IconSource {
  src: string
  mode: 'mask' | 'img'
  /** Per-stroke-width variant files, keyed by the strokeWidth prop value the call site passes.
   *  External files freeze stroke weight, so each non-default weight in use gets its own exported
   *  file (see export-icons.mts REGISTRY_EXPORTS). */
  weights?: Record<string, string>
}

const B = publicAssetPath('icons/brand')
const U = publicAssetPath('icons/utility')

export const ICONS: Record<IconName, IconSource> = {
  close: { src: `${U}/close.svg`, mode: 'mask' },
  plus: { src: `${U}/plus.svg`, mode: 'mask' },
  copy: { src: `${B}/05-copy.svg`, mode: 'mask' },
  pencil: { src: `${B}/03-draft.svg`, mode: 'mask' },
  trash: { src: `${B}/04-trash.svg`, mode: 'mask' },
  'chevron-left': { src: `${U}/chevron-left.svg`, mode: 'mask' },
  'chevron-right': { src: `${U}/14-chevron.svg`, mode: 'mask' },
  'chevron-down': { src: `${U}/chevron-down.svg`, mode: 'mask' },
  journal: { src: `${B}/02-journal.svg`, mode: 'img' },
  spark: { src: `${B}/01-ai.svg`, mode: 'img' },
  bell: { src: `${U}/02-bell.svg`, mode: 'mask' },
  target: { src: `${U}/target.svg`, mode: 'mask' },
  search: { src: `${U}/13-search.svg`, mode: 'mask', weights: { '1.6': `${U}/search-thin.svg` } },
  calendar: { src: `${U}/01-cal.svg`, mode: 'mask' },
  clock: { src: `${U}/03-clock.svg`, mode: 'mask' },
  check: {
    src: `${U}/check.svg`,
    mode: 'mask',
    weights: { '2.4': `${U}/check-bold.svg`, '3.4': `${U}/check-heavy.svg` }
  },
  image: { src: `${U}/09-image.svg`, mode: 'mask' },
  'arrow-up': { src: `${U}/arrow-up.svg`, mode: 'mask' },
  repeat: { src: `${U}/repeat.svg`, mode: 'mask' },
  location: { src: `${U}/location.svg`, mode: 'mask' },
  notes: { src: `${U}/notes.svg`, mode: 'mask' },
  info: { src: `${U}/11-info.svg`, mode: 'mask' },
  sync: { src: `${U}/sync.svg`, mode: 'mask' },
  mail: { src: `${U}/mail.svg`, mode: 'mask' },
  reset: { src: `${U}/12-reset.svg`, mode: 'mask' },
  'spark-mono': { src: `${U}/spark-mono.svg`, mode: 'mask' },
  'journal-plain': { src: `${U}/journal-plain.svg`, mode: 'mask' },
  'x-small': { src: `${U}/x-small.svg`, mode: 'mask' },
  'pencil-small': { src: `${U}/pencil-small.svg`, mode: 'mask' },
  'calendar-alt': { src: `${U}/calendar-alt.svg`, mode: 'mask' },
  tomato: { src: `${B}/pomodoro-tomato.svg`, mode: 'img' },
  'view-day': { src: `${B}/09-day.svg`, mode: 'img' },
  'view-week': { src: `${B}/08-week.svg`, mode: 'img' },
  'view-month': { src: `${B}/07-month.svg`, mode: 'img' },
  'view-list': { src: `${B}/10-list.svg`, mode: 'img' },
  gear: { src: `${B}/11-gear.svg`, mode: 'mask' },
  brush: { src: `${U}/brush.svg`, mode: 'mask' },
  globe: { src: `${U}/04-globe.svg`, mode: 'mask' },
  star: { src: `${U}/star.svg`, mode: 'mask' },
  layers: { src: `${U}/layers.svg`, mode: 'mask' },
  home: { src: `${U}/home.svg`, mode: 'mask' },
  lock: { src: `${U}/05-lock.svg`, mode: 'mask' },
  heart: { src: `${U}/heart.svg`, mode: 'mask' },
  work: { src: `${U}/work.svg`, mode: 'mask' },
  users: { src: `${U}/07-users.svg`, mode: 'mask' },
  school: { src: `${U}/school.svg`, mode: 'mask' },
  bulb: { src: `${U}/bulb.svg`, mode: 'mask' },
  eye: { src: `${U}/10-eye.svg`, mode: 'mask' },
  note: { src: `${U}/08-note.svg`, mode: 'mask' },
  shield: { src: `${U}/06-shield.svg`, mode: 'mask' }
}

/** CdEventChip's quadrant mini-icon files (masked with the quadrant color at the call site).
 *  Not IconName glyphs — the chip renders them at 10px inside its own layout, not through CdIcon. */
export const QUAD_ICON_SRC: Record<'do' | 'plan' | 'quick' | 'later' | 'event', string> = {
  do: `${U}/quad-do.svg`,
  plan: `${U}/quad-plan.svg`,
  quick: `${U}/quad-quick.svg`,
  later: `${U}/quad-later.svg`,
  event: `${U}/quad-event.svg`
}
